
services:
  web:
    image: python:3.9.22
    ports:
      - "8005:8000"
    volumes:
      - .:/usr/app
    working_dir: /usr/app
    command: >
      sh -c "sleep 5 &&
             pip install --no-cache-dir -r requirements.txt &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"